<?php
  // BDTD: página inicial própria (faixa com título, contadores e busca; atalhos; parceiros).
  $this->headTitle($this->translate('BDTD'));

  // Disable top search box and notices -- this page has a special layout.
  $this->layout()->searchbox = false;
  $this->layout()->disableDefaultNotices = true;
  $this->layout()->layoutFull = true;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $config = $this->config()->get('config');
    $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
  }

  $this->breadcrumbs()->disable();
  $this->assetManager()->appendScriptLink('indicators-home.js');
?>
<div class="search-box">
  <div class="container">
    <div class="box-title">
      <h1 class="bdtd-title">Biblioteca Digital Brasileira de <br> Teses e Dissertações</h1>
      <p class="bdtd-subtitle h4">Acesso e visibilidade às teses e dissertações brasileiras</p>
    </div>

    <?=$this->render('search/bdtd-indicators.phtml')?>

    <?php $this->slot('search-home-hero')->start() ?>
      <?=$this->context($this)->renderInContext('search/searchbox.phtml', ['focusOnLoad' => true, 'ignoreHiddenFilterMemory' => true])?>
    <?=$this->slot('search-home-hero')->end() ?>
  </div>
</div>

<?=$this->notices()->renderNoticesForPosition('default')?>

<div class="container">
  <div class="search-info bottom-search-form">
    <a class="item" href="<?=$this->url('participate-home')?>">
      <div class="text-primary flex-row-spaced-between">
        <h2 class="main-highlight h4">Participe</h2>
        <?=$this->icon('bdtd-participate')?>
      </div>
      <p>Faça parte da BDTD e contribua com a disseminação das teses e dissertações produzidas por pesquisadores brasileiros.</p>
    </a>
    <a class="item" href="<?=$this->url('technology-home')?>">
      <div class="text-primary flex-row-spaced-between">
        <h2 class="main-highlight h4">Tecnologia</h2>
        <?=$this->icon('bdtd-technology')?>
      </div>
      <p>Em concordância com os preceitos da Ciência Aberta, toda a tecnologia utilizada para o funcionamento da BDTD são de código livre.</p>
    </a>
    <a class="item" href="<?=$this->url('indicators-home')?>">
      <div class="text-primary flex-row-spaced-between">
        <h2 class="main-highlight h4">Indicadores</h2>
        <?=$this->icon('bdtd-indicators')?>
      </div>
      <p>Acesse alguns indicadores quantitativos relativos às teses e dissertações no Brasil.</p>
    </a>
  </div>
</div>

<div class="container">
  <?=$this->render('content-home.phtml')?>
</div>
