; BDTD — meta tags nos registros (Dublin Core e Highwire Press para o Google Acadêmico).
[Parent_Config]
relative_path = ../../../config/vufind/metadata.ini

[Vocabularies]
Bdtd\RecordDriver\SolrDefault[] = DublinCore
Bdtd\RecordDriver\SolrDefault[] = HighwirePress
