<?php
  // Set up breadcrumbs:
  $this->breadcrumbs()->reset();
  if ($url = $this->searchMemory()->getLastSearchUrl()) {
    $this->breadcrumbs()->add($this->translate('Search'), $url);
  }
  $this->breadcrumbs()->add(...$this->recordLinker()->getBreadcrumbParams($this->driver))
    ->add($this->translate('Record Citations'), active: true);

  // Collect citation data:
  $helper = $this->citation($this->driver);
  $citations = [];
  foreach ($this->driver->getCitationFormats() as $format) {
    $citations[$format] = $helper->getCitation($format);
  }
?>
<?=
  // Set page title and heading.
  $this->component('page-title', [
    'title' => $this->translate('Record Citations'),
    'level' => 1,
  ])
?>
<?php if (count($citations) == 0): ?>
  <?=$this->transEsc('No citations are available for this record')?>
<?php else: ?>
  <?php foreach ($citations as $format => $citation): ?>
    <?php
      // Some language files only contain translations for a short caption;
      // let's try to detect whether or not long captions are getting translated
      // properly and display the appropriate one accordingly. This logic can be
      // removed once all of the language files contain the "Edition Citation"
      // version of the relevant strings.
      $shortCaption = $this->translate($format . ' Citation');
      $longCaption = $this->translate($format . ' Edition Citation');
      $caption = (strpos($longCaption, 'Citation') > 0 && !str_contains($shortCaption, 'Citation'))
        ? $shortCaption : $longCaption;
      $elementId = 'citation-' . $this->escapeHtmlAttr($format);
    ?>
    <strong><?=$this->escapeHtml($caption)?></strong>
    <div class="citation copy-to-clipboard-container">
      <span id="<?=$elementId?>">
        <?=$citation?>
      </span>
      <?=$this->copyToClipboardButton('#' . $elementId)?>
    </div>
  <?php endforeach; ?>
  <?php /* BDTD: nota sobre o estilo ABNT e o Zotero */ ?>
  <div class="text-muted text-center">
    <?=$this->transEsc('ABNT Citation Note')?>
    <a href="https://zenodo.org/record/6376312" target="_blank" rel="noopener noreferrer">Zotero</a>
    <?=$this->transEsc('ABNT Citation Note2')?>
  </div>
<?php endif; ?>
